"""avatar-hash

Revision ID: 374a18eaeac7
Revises: 12c6bb49f573
Create Date: 2016-11-10 00:36:49.483309

"""

# revision identifiers, used by Alembic.
revision = '374a18eaeac7'
down_revision = '12c6bb49f573'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # op.drop_column('users', 'new_email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('new_email', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
