"""join confirmed

Revision ID: c8ebcd4485f5
Revises: 456a945560f6
Create Date: 2016-11-08 20:46:07.633192

"""

# revision identifiers, used by Alembic.
revision = 'c8ebcd4485f5'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
