"""user-role

Revision ID: fc875987612b
Revises: c8ebcd4485f5
Create Date: 2016-11-09 21:13:13.807606

"""

# revision identifiers, used by Alembic.
revision = 'fc875987612b'
down_revision = 'c8ebcd4485f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # op.drop_column('users', 'new_email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('new_email', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
